### ISSUE TITLE
Create a Ripple Animation for Buttons (10)

### ISSUE THREAD

**Issue by mschroederi** [hpi-swa-teaching/SWT18-Project-13#10]
As a user I want to see where I clicked on the Flat, Raised or FloatingAction Button.

[example of the ripple animation](http://materializecss.com/buttons.html)

- [x] a parameter exists that denotes the animation duration
- [x] the ripple appears, fill the bounds of the given rectangle and fades out
- [x] show multiple ripples when clicking more than one time within the duration
- [x] hold animation inside the button

**Comment by lassesteffen** [comment]
- translucent
- BezierCurve erstellen und umdrehen, dazu 4 * 3 Werte hinzufügen (für eine Ecke) die wieder bei radius Top ankommen
- die Werte in ein genestetes Array packen (12 Werte pro Ecke), dann drawGeneralBezierShape aufrufen
