### ISSUE TITLE
Fonts (4)

### ISSUE THREAD

**Issue by CarolinGoerke** [hpi-swa-teaching/SWT18-Project-13#11]
As a user I want to see the font Roboto and the headlines should be bold.

**Comment by mschroederi** [comment]
Beim setzten des Labels:
* check ob Roboto installiert
* wenn ja: addNewFontSize
* wenn nein: default Schriftart wählen --> wenn isTtcFont = true --> addNewFontSize mit Größe nach MaterialDesign Guideline

**Comment by mschroederi** [comment]
```
TTCFontReader encodingTag: 0.
TTCFont newTextStyleFromTTFile: (FileDirectory uri: 'Roboto/Roboto-Bold.ttf') fullName
```
