### ISSUE TITLE
Buttons follow the Material Guideline Specs (5)

### ISSUE THREAD

**Issue by lassesteffen** [hpi-swa-teaching/SWT18-Project-13#27]
As a User I want my buttons to look like specified by the Material Guidelines. They should implement the following standards:

- [x] height and width should conform to standard
- [x] auto scale the button when bigger text is entered
- [x] 16 dp to the sites from the text
- [x] Text should be all caps

More at: [Button Specs](https://material.io/design/components/buttons.html#specs)

**Comment by TheNotoriousGit** [comment]
Fixed in "Implement material standard for buttons and add the flat button."
