### ISSUE TITLE
Create Floating Action Buttons (3)

### ISSUE THREAD

**Issue by CarolinGoerke** [hpi-swa-teaching/SWT18-Project-13#6]
As a user I want to click a "Floating Action Button" to add new classes/methods/whatever.
https://material.io/guidelines/components/buttons.html#

- [x] rounded corners
- [x] use icons (depends on [Import Material Design Icons](https://github.com/hpi-swa-teaching/SWT18-Project-13/issues/15))

**Comment by lassesteffen** [comment]
#59
