### ISSUE TITLE
Menus (3)

### ISSUE THREAD

**Issue by mschroederi** [hpi-swa-teaching/SWT18-Project-13#68]
- [x] we can open the menu by clicking on a button
- [x] specify text and icon
- [x] has shadow
- [x] close on item select
- [x] close on background click
- [x] has nested menus

API like in MenuItemMorph and MenuMorph

**Comment by tom95** [comment]
- [ ] align icons and text
- [ ] open nested on hover and close it again when left
- [ ] close nested as well when main is closed
- [ ] open all menus (nested or not) in a way that doesnt collide with screen edges, if possible

**Comment by tom95** [comment]
Still todo
- [ ] first menu also avoids colliding
- [ ] ripples appear when clicking

also above unmarked items

**Comment by lassesteffen** [comment]
Fixed in #96
